export const CHANGE_FORM = "CHANGE_FORM";
export const FETCH_BOOKS = "FETCH_BOOKS";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const ACTIVATED_BOOKPAGE = "ACTIVATED_BOOKPAGE";
export const DISACTIVATED_BOOKPAGE = "DISACTIVATED_BOOKPAGE";